#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tinyrpc
Version  : 1.0.4
Release  : 13
URL      : https://files.pythonhosted.org/packages/9d/91/c639ba014aada92446516c5fc4b04f2cee3539ab2d0758a6a87a6da973cb/tinyrpc-1.0.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/9d/91/c639ba014aada92446516c5fc4b04f2cee3539ab2d0758a6a87a6da973cb/tinyrpc-1.0.4.tar.gz
Summary  : A small, modular, transport and protocol neutral RPC library that, among other things, supports JSON-RPC and zmq.
Group    : Development/Tools
License  : MIT
Requires: tinyrpc-license = %{version}-%{release}
Requires: tinyrpc-python = %{version}-%{release}
Requires: tinyrpc-python3 = %{version}-%{release}
Requires: Werkzeug
Requires: gevent
Requires: msgpack
Requires: pyzmq
Requires: requests
Requires: six
Requires: websocket_client
BuildRequires : Werkzeug
BuildRequires : buildreq-distutils3
BuildRequires : gevent
BuildRequires : msgpack
BuildRequires : pyzmq
BuildRequires : requests
BuildRequires : six
BuildRequires : util-linux

%description
tinyrpc: A small and modular way of handling web-related RPC
============================================================

%package license
Summary: license components for the tinyrpc package.
Group: Default

%description license
license components for the tinyrpc package.


%package python
Summary: python components for the tinyrpc package.
Group: Default
Requires: tinyrpc-python3 = %{version}-%{release}

%description python
python components for the tinyrpc package.


%package python3
Summary: python3 components for the tinyrpc package.
Group: Default
Requires: python3-core

%description python3
python3 components for the tinyrpc package.


%prep
%setup -q -n tinyrpc-1.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572798924
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tinyrpc
cp %{_builddir}/tinyrpc-1.0.4/LICENSE %{buildroot}/usr/share/package-licenses/tinyrpc/5e4d7d32b7f34e61b6d7a39e9073ea8b5605e6c2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tinyrpc/5e4d7d32b7f34e61b6d7a39e9073ea8b5605e6c2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
